### ISSUE TITLE
MIUI Info , Layout problem in French

### ISSUE THREAD

**Issue by Taken1403** [ingbrzy/MA-XML-9.0-FRENCH-Global#2]
With Xiaomi Mi5X , 9.0.3.0 By Xiaomi.eu . Default Font . https://drive.google.com/file/d/1sYgTRtRGrWLIA5Fq4E67kxYs8v5JYY_O/view?usp=drivesdk

**Comment by Taken1403** [comment]
Like Snapdragon 820 (Not 820 is 625)

**Comment by ingbrzy** [comment]
fixed for next version
